save-position-on-quit=yes
watch-later-directory=~/watch_later
volume=50
osd-bar=no
image-display-duration=inf

hr-seek=yes
hr-seek-demuxer-offset=5

hwdec=auto-safe
cache=auto
cache-secs=60

cache-pause=yes
cache-pause-wait=5

ytdl-format=bestvideo+bestaudio/best

[protocol.http]
cache=yes
cache-secs=60
cache-pause=yes
cache-pause-wait=5

[protocol.https]
cache=yes
cache-secs=60
cache-pause=yes
cache-pause-wait=5
