slang=en

save-position-on-quit=yes
watch-later-directory=~/watch_later
volume=50
osd-bar=no
image-display-duration=inf

hr-seek=yes
hr-seek-demuxer-offset=5

hwdec=auto
video-sync=audio
profile=fast
cache=auto
cache-secs=180

demuxer-readahead-secs=8
demuxer-max-bytes=256MiB
demuxer-max-back-bytes=128MiB

cache-pause=yes
cache-pause-wait=2

[sshfs]
cache=yes
cache-secs=20
demuxer-thread=yes
demuxer-readahead-secs=10
demuxer-max-bytes=384MiB
demuxer-max-back-bytes=192MiB
cache-pause=yes
cache-pause-wait=2

[protocol.http]
cache=yes
cache-secs=180
cache-pause=yes
cache-pause-wait=2

[protocol.https]
cache=yes
cache-secs=180
cache-pause=yes
cache-pause-wait=2
