slang=en

save-position-on-quit=yes
watch-later-directory=~/watch_later
volume=50
osd-bar=no
image-display-duration=inf

hr-seek=yes
hr-seek-demuxer-offset=5

hwdec=auto-safe
video-sync=audio
cache=auto
cache-secs=180

demuxer-readahead-secs=20

demuxer-max-bytes=512MiB
demuxer-max-back-bytes=128MiB

cache-pause=yes
cache-pause-wait=5

ytdl-format=bestvideo+bestaudio/best

[sshfs]
cache=yes
cache-secs=20
demuxer-thread=yes
demuxer-readahead-secs=10
demuxer-max-bytes=384MiB
demuxer-max-back-bytes=192MiB
cache-pause=yes
cache-pause-wait=2

[protocol.http]
cache=yes
cache-secs=60
cache-pause=yes
cache-pause-wait=5

[protocol.https]
cache=yes
cache-secs=60
cache-pause=yes
cache-pause-wait=5
