# Font
font_family JetBrains Mono
font_size 12

# Window
background_opacity 0.50
inactive_text_alpha 0.2
window_padding_width 1
# Cursor
cursor_shape block
cursor_blink_interval 0

# Scrollback
scrollback_lines 10000

# Colors
#foreground #cdd6f4
#background #1e1e2e

