
##################
### WINDOWRULE ###
##################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

xwayland{
    force_zero_scaling = true
}

cursor {
    inactive_timeout = 1
    hide_on_key_press = true
}

windowrule = match:workspace special:magic, border_size 0, center on
windowrule = match:workspace special:virt, border_size 0, center on

#special workspace
windowrule = match:class ^(.*[Dd]iscord.*)$, workspace special:magic silent
windowrule = match:class ^(.*[Ss]potify.*)$, workspace special:magic silent
windowrule = match:class ^(.*[Tt]elegram.*)$, workspace special:magic silent
windowrule = match:class ^(.*WhatsApp.*)$, workspace special:magic silent

windowrule = match:class ^(virt.manager)$, workspace special:virt silent 

windowrule = match:class ^(obsidian)$, workspace special:obsidian silent


windowrule = match:class ^(steam)$, workspace 9 silent
windowrule = match:class ^(brave-browser)$, workspace 1
windowrule = match:class ^(librewolf)$, workspace 1
windowrule = match:class ^(mpv)$, workspace 3

windowrule = match:float on, stay_focused on

windowrule = match:fullscreen_state_internal 1, border_size 1

